#!/bin/sh
#
# This file was automatically generated by the Nios II IDE Flash Programmer.
#
# It will be overwritten when the flash programmer options change.
#

cd F:/AX301/TEST/DEMO_N/hello_world/Debug

# Creating .flash file for the FPGA configuration
"$SOPC_KIT_NIOS2/bin/sof2flash" --epcs --input="F:/AX301/TEST/DEMO_N/HELLO.sof" --output="HELLO.flash" 

# Programming flash with the FPGA configuration
"$SOPC_KIT_NIOS2/bin/nios2-flash-programmer" --epcs --base=0x00000000 --sidp=0x00001900 --id=0 --timestamp=1395936883 --instance=0 "HELLO.flash"

# Creating .flash file for the project
"$SOPC_KIT_NIOS2/bin/elf2flash" --epcs --after="HELLO.flash" --input="hello_world.elf" --output="epcs.flash"

# Programming flash with the project
"$SOPC_KIT_NIOS2/bin/nios2-flash-programmer" --epcs --base=0x00000000 --sidp=0x00001900 --id=0 --timestamp=1395936883 --instance=0 "epcs.flash"

